### ISSUE TITLE
CPU module not working.

### ISSUE THREAD

**Issue by rrotaru** [rrotaru/CS385-CPU#6]
Test output for the CPU modules gives us a lot of "don't care" values (x's) where we should be getting output. Traced this down to a problem in either regfile or something to do with the register file modules, where we are getting don't cares for `A` and `RD2` on line 104 of MIPS-CPU.vl

```
    reg_file rf (IR[11:10], IR[9:8], WR, AluOut, RegWrite, A, RD2, clock);
```

when we should be getting real values.

Anyone else let me know if you can get to the bottom of this. I'm trying to work on it but I don't think I understand the register file enough to make progress.

**Comment by BrBigelow** [comment]
Lines 29 to 31 - c1, c2, and c3 are clock values. But the way he has them set to go in are as undeclared wires.

**Comment by BrBigelow** [comment]
Nevermind - seems the decoders are setting those. Hrm.

**Comment by rrotaru** [comment]
Markov's notes for the assignment seems to say:

```
change the D flip-flops with 16-bit registers
```

Have we done that? It looks like we are just using 16-bit D flip-flops. Is that the same thing?

**Comment by BrBigelow** [comment]
?Yes - D-Flip-Flips can be used to represent registers. In this case, we had to replace the regular ones with 16-bit. Which we did. Not that we did it right mind you. Just that the premise is correct.
